services:
  coap-server:
    build: .
    image: tp-coap:latest
    container_name: coap-server
    ports:
      - "5683:5683/udp"      
      - "5684:5684/udp"      
    networks:
      - coap-network
    command: python server.py

  coap-client:
    build: .
    image: tp-coap:latest
    container_name: coap-client
    stdin_open: true
    tty: true
    command: sleep infinity
    depends_on:
      - coap-server

networks:
  coap-network:
    driver: bridge